language: java

jdk:
  - openjdk17

# Need a full git clone in order to be able to tag the release
git:
  clone: false

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout $TRAVIS_BRANCH
  - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed -e 's/-SNAPSHOT//')
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
  - gpg --fast-import .travis/gpg.asc

env:
  global:
    # Environment variables referenced in .travis/maven-settings.xml. To encrypt and escape values correctly, run the following
    # command and enter ENV_VAR=value when prompted:
    # read -r && travis encrypt "$(printf %q "$REPLY")"
    - secure: gWu4psx9R1rd2BdTrZwHukwq4wBcRMq+bOKkzjhHt1oFOxkGsH/REv63qp3LIZuUiKo9dDRkLwGeYYAqgHrmUZjQ6mYIXQDKW/qzehJeZIpI4Zpa2pXgj5ZiuDZiTeStk++W7T0Ofk8aPrYc+UUtdQN4X03EQTDh9BSOBOI9IW6rKQHZiXKEbOOs2FwR4Ff5z1Q80VCFJmZIu9zw/dyjbuBoauFkuTVFwWygEd/thzw/5fzC9VLYCJIzwl5oVFgMSwXP8UoFe7UEW3Sa78khgfpIkQWG1CobP0zxle0E9TEbarMe7oM0equvuennd9+a3nzuQoulbeTnEtz3pd9mCuEIn/1/pQBVboyB21lVS9zLY/gNczRQKXpBubKp7SV3D3MoKJOkS038grZhIlZJtvY/KDI25TUXxr9Vw/dqs2h3DMKZJHfp4vjTNN+6AgttIwSu9sAR6ERFd1bEvuhDHQYbH+lgBx/qjoKeOiC3Dr6VW4LS0gOyW1OPD10QOWARmaquRKL01veyrHgMwGEyNb+Iu5kB1P6PQBaKYruy1pO12h6Hl/M1B+oDtFtlnsYLHRKiAgc7ba2TAGFpjKfoEW3QkLqbDVlnlzWLhi7n+qUh2SymBv3bo+24n1jN27HjKBbsUJqQsoNkxciQwDwP5sFjPLDv4xaLQifP8Aop7rs=
    - secure: A7Uw9X0ARV8ykK8wxH+/lIfbUU9GlN9Ng5DE3T74um/btd5d2YGIh2gj6+xtu2fJXnjTEUmqlbQzpdFuY/tXZpwoBkEqrEEhEwE35OlQm7utHPueb4/lzhm3PQcGjmO6kJDPY9eOpzCon70MRg/2jCb4jT6CzZLqQ492aXEgfqRrGFgdgkNcwwW5jWPhi8LuRGQvPnktO27cX696tulLMIBvHH49poY7rJHpFo+TdnghUsmIIr/Nij5gvZJeF5leBuM21bwj6ZpB+UvpsTSSu1gY++uJxtY1jmuAvhlEaJW2cU6SkqG0BqSey+G0pZVk0FynSrhbt90qberqDLIbOkyfQQPeyAZIl0r8+Lz3x5UfO5jJeIEs/zFpdFIOp3bGs3GQoPQRel2minbJVOSWLEDpelW53IPQuYF78EvuQ7fXp88otUkO7R/nn6MvcoLB5jWmrmvJ7bc3thSHf0jnFLFBpLeUc7FDcXnZv7MhhqJvPWAkbPJNoJ6MH/AhYzrn6sfSIkC2u/8BTnKT2MIIf45OQoUfgnZpwxTCk9CXkNUVafXXjlXxpmiBeO5isCcdiDouRg5hbqyqjpfwDpJnLrJ1vRCb84lM/kKoRnjsGMCVkv4TF1k5wdXHGSCkdO25mM8ZH3FFYpvuvcj9TgPG8SJVmISzOR7Cd+YzqMoPenQ=
    - secure: WyNUCNQ4U3gTB5z4McyBP1T7saqDDQDwfoKUUTkuJdJAfyl6kAkKFIoacGV+MqWpHJnoZf5kmkgfkXgyd7QyTg4nDuCY2RWAUIBUqLapRLPLrOJPeTSaGVge1qe1N3+4kRw+tqL0CVq/Svb5FHNNEyGWn4/+cH4ssJKKi5u9vl1I9Pj3wprl9cVFQH1CnxVdkvsIc8UbRdFIWtN1rvHwl2HVw5BjuzjLDLnE5dxRy0ZpvmdsS6ykeIrVRIoEzJOOyLdkwSLsSU4B8JOvDqTz3ModTZDaAcHuIYuy5P4UgrDrxGkdb1+RVQcmupXhUTyHLX+J/humwkUNYNo4FQvKosBPrK0MvCRCR5rjy570x+dHSEeD7DZFnU/fpDHYyJrevZ8IdjiSzj+FPRpJ7sNRNti22xyf570oYlzxCX+UcWdVEgbnZ9Ml+SSr2lw6Nyr7fIp/5othjJa3LDDtRkslA4zBOQ11nQeiZ7opEhzkQuT9nL1XKhgdUpmqDuDklpRZQAds/XbvjcbQOGyxq3svk1rT8vMI3edtq5OYJNYAbAlZx//KtcTBKP5I8SFetHp6sJMYvGcUOWcwLCR3NwCTvGFx39qF1U/gZiK5Rpj7/bo0di8I/hLnHmgD9EG2s1KbiyPwWBQvhkQysCUcUZ2tluIUFjIN30ZocF+Wih+DrBc=
    - secure: Ml4TnRVqSzfpIzz2Ps2+QpmJQ8tirSj2pjmz0Vi4zAVYIfCQdgTx7xo4jcGJQ3hJJRHYujS2UwMLgy1cBnvd48UIFILkkiE3ATOLvki7/WRyzXTLcRiIDJdAXfLc4cVW0leU/2T30QS8YLC3MMZ7bs/VO9UsiMHGSJY7junkidtTV0XPSuHKKWFxp3m6Pf6Xd0FMbynQoDDHL7MebVVu/ifCx7jnWjGTQlZTvG4m9wfPdbhMpbd8oeTln/Eouj92pefrRT3oHT1i+ElDaNpTw99ZY8j1Hm1uWOYUOLNwGtfLzBoW+QYuZ6AiV70oEocQDoCPMMMoRPz/WK/03DCOFWSZbRpqxIgfr60L7dJl3yBSX6dsMSOiifBEhF42lgTbqcnzNf1mN9EU6YaN+Dx5tGy6EFKZgEqZx/Wk7H2/7+oBLokc5dTARfgCtMeyjA/H/NYc+2xsd5VIqQ0vqOvH2U7hVaTUOEZJc3qBOzDc74X3jSNdiwxFLMvlPf8ZHKWPivDlm+oCgo/WxPKmiwjRhmMihexZrY3Ja0pv6sn0/NG3xcT4+WOjxt3pr+WqO6lhp2PinqV6u6vjpMO9SlcfIrxm+YgI7h+KlyVO9Ywc/M5pt9eYXo2HoG3d2Iql7LJbP/YQr74iLFcXYvj6SUSc/L3g2Fp4A0lvnYyblSCc/3M=
    - secure: bBC/LyYh7Qz36FodQtBkbSnF2eNYeHQ4eYE5IeJXhINtq8ikTeyKor83INTcpZMJh58bPibINocNzOmrl6Y0JSVwcDfYncGPgZqyb2G1fWQFrsZsggcqSwMTcQh1/LDLWMHLU6fA3iTVvMYUKUmwGBId2SJFbALtNrqk1IrJUV+Is3Yk//9GFaY790he2Su9xWyeOdJiXEaGeA+IB8S/Kfc0nJ5l+M4K+1gDfQwkc4VMD6xa2bvaJU6raaIaCxPEqsdp1uJmeQzfFC/pLH5hSQtIrOWNHXoLnESs0Ce5p5TXPdEsIUajwjSWBAd03oUpEYdfwq9Wvh1rY642ISiTeaUs6etf7K3L9xGfdcZJkVIcfnws2QsNnNVaoEdVdDWi3Q2RAm1WfN5iApgyp50JIIoIajRxiAnUzSXBILHoLwz2qI+kF52w4EiwNxOV3CE529TE0KVg8vUG8qDMXhl9V7J4KmqJ65nFj7wkgsL/aMCOGuUWW6E0FuLYcUX8yZBGf6AAEM0inGijLPXxF/QBq3a6BLMlFhbpBh4HKUZYS1hxICHdG3S4pcQdHrrJtGd7qHtDAv9bsvukzAmQdAuZg6MG3v1K3QbgP5zQnM/2t2Fo5epWFXKmV8D+Lyqa3Xq0By8QjvbFBTmNZaq5ojroHBwW9/HV6+ZlCtL84MGp3NQ=

script:
  - mvn clean install -B
  - mvn org.pitest:pitest-maven:mutationCoverage -B

before_deploy:
  # Set tag to be used by releases provider
  - export TRAVIS_TAG=$POM_VERSION

deploy:
  # For any checkin to main branch, create a final version, tag it and push the artifacts to Sonatype
  - provider: script
    skip_cleanup: true
    script:
      mvn --settings .travis/maven-settings.xml release:prepare release:perform -DskipTests -Prelease -B
    on:
      branch: main

  # Releases config copied from https://docs.travis-ci.com/user/deployment/releases/ and secure key generated by following
  # https://stackoverflow.com/questions/25302518/travis-ci-setup-releases-with-github-token#answer-57032190
  - provider: releases
    api_key:
      secure: ZTZd3Pi7YAVrvIrUyJHhlYs2ON7MJ6vEoCDeQmFNBtD9YnDwbReDKRHxYGYjGp/lzGUwDWOF1ROS48XHWz5g9dIlW9y4M+PB/VBqxzSjA1QHuSVyWuaFXis92MVC5s2k5HzIYMdY713jAIILPmx2BAexNEHGP10smCcSDGJmF2pUBntTsFf2hgQhS3bpMf6ZX22k2iL2sKeobTlM7sI6pKGCP61qOKIfRwPK4rzJC1aNNB4a3KiSmIcXKPFQrF+Cs71jP/FfHam/j75/vUmFIqE8xzNPiCboxWaa/Bz2oS3nMfzoBL4aMwvdkFI6a6Tsog5uiwQVjfmDjgIIikWkM0OvFUkLeId027IWk7MvOTSGw4ReBLz4AcM1H4EXhjfI5v7tdqVYKTyAszStYYTwOGp255a4ZRXlKFBLPLKEeZsGyHI+kWgeqyjLC2orw09/UR0fwTeI+INC9ojZcc0/ubonuRL8igz1Zghys7Wibn869yRaWQtac50qo9DNJFrKKPwnG8jP3R3gQbaMkXpEeU0JJvvQOKDVdK665E4LBfgmmEkBQPxj+A6FyykNAPgiFjsn32Ymf4oGmTBly5bIVMNwRRACuFeG78EOPrl8XCkDCBzP8E0i4rHIrhG75+p0F5isebBtyzJhnLMgU9SxRhEObfQ0Zf25u+81AOqYYQM=
    file: "target/spt-development-audit-spring-${POM_VERSION}.jar"
    skip_cleanup: true
    on:
      branch: main